// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7Fh4AVLbECIOP2l1G8xNJX4z5RbM1yi4',
    appId: '1:638531123568:web:ed9bf47f99111e0537f7b5',
    messagingSenderId: '638531123568',
    projectId: 'word-generate',
    authDomain: 'word-generate.firebaseapp.com',
    storageBucket: 'word-generate.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZUI6lMNB2rPqK2ewdElQM7_BuicRzQ3w',
    appId: '1:638531123568:android:d0c803eb4f60c2a437f7b5',
    messagingSenderId: '638531123568',
    projectId: 'word-generate',
    storageBucket: 'word-generate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOgJmUzHQMlLTrryfny2PQBxJGfL1Nins',
    appId: '1:638531123568:ios:3884179cceb7bd2337f7b5',
    messagingSenderId: '638531123568',
    projectId: 'word-generate',
    storageBucket: 'word-generate.appspot.com',
    iosClientId:
        '638531123568-k1frdf9f1llvnioqahbu98pbapslgtlj.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOgJmUzHQMlLTrryfny2PQBxJGfL1Nins',
    appId: '1:638531123568:ios:3884179cceb7bd2337f7b5',
    messagingSenderId: '638531123568',
    projectId: 'word-generate',
    storageBucket: 'word-generate.appspot.com',
    iosClientId:
        '638531123568-k1frdf9f1llvnioqahbu98pbapslgtlj.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFlutter',
  );
}
